#[Info]
site_name: 白泽的知识库
site_url: https://wiki.baize.host
site_author: 白泽
theme:
  name: material
  custom_dir: overrides
  # custom_dir: material/.overrides
  font:
    text: Bitter
    code: Roboto Mono
  logo: https://baize2.imgix.net/202311111507861.jpeg
    # material/library
  admonition:
    <type>: material/file-alert-outline
#[ui]
  favicon: img/baize.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: bblue grey # 上方的
      accent: indigo # 链接等可交互元件的高亮色
      # teal 
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black 
      accent: indigo
      # teal
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features: 
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    # - navigation.instant 
    #- header.autohide  #自动隐藏
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - content.tabs.link
    - content.tooltips
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.code.annotate 
  language: zh # 一些提示性的文字会变成中文
  icon: 
    repo: fontawesome/brands/github #右上角图标
edit_uri: edit/master/docs # 编辑按钮跳转的链接 
repo_url: https://github.com/yanpuzhen/docs # 右上角点击跳转的链接
repo_name: 前往我的主页 # 右上角的名字
# [Navigtion]
nav:
  - 主页: index.md
  - 技术:
    - Linux:
      - Linux服务器必备软件: blog/linux-server.md
      - Linux桌面版必备软件: blog/linux-desktop.md
    - Windows:  
      - windows必备软件: blog/windows.md
    - 白嫖攻略:
      - 互联网白嫖指南: blog/internet.md
    - 开源推荐:
      - 开源产品推荐: blog/open.md
    - 自建网址导航: blog/nav.md
  - 牢骚: blog/laosao.md
  - blog: https://blog.baize.host
  - 标签: tag.md
  - 关于: about.md
  - 友链: link.md

# [版权声明]
copyright: Copyright &copy; 2022~2077 Wcowin/All Rights Reserved. # 左下角的版权声明

#[extra]
extra:
  generator: true  #删除页脚显示“使用 MkDocs 材料制造”
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/yanpuzhen
  - icon: fontawesome/brands/qq
    link: tencent://message/?uin=1304668140&Site=qq&Menu=yes
  - icon: fontawesome/regular/envelope
    link: mailto:<admin@ipv6.email>
  - icon: fontawesome/brands/bilibili
    link: https://space.bilibili.com/68016127?spm_id_from=333.999.0.0
  analytics:
    provider: google
    feedback:
      title: 此页面有帮助吗？
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            谢谢你的反馈！
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            谢谢你的反馈！
  consent:
    title: Cookie consent
    description: >- 
      我们也使用cookies来识别您的重复访问和偏好来衡量我们文档的有效性以及用户是否找到他们要找的东西。
      如果你同意,你可以帮助我们让我们的网站更好
# [Plugins]
plugins:
  #- glightbox
  - search
  - blog:
      post_date_format: full #时间
      draft: true
      draft_if_future_date: true #自动将具有未来日期的帖子标记为草稿
      post_readtime: true
      post_readtime_words_per_minute: 265  #计算帖子的阅读时间时读者每分钟预计阅读的字数
      post_url_format: "{date}/{slug}"
      categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      # categories_toc: true
      # pagination_per_page: 5
      pagination_url_format: "page/{page}"
      authors_file: "{blog}/.authors.yml"  #作者信息
  - tags:
      tags_file: tag.md  #分类标签 



# [Markdown]
markdown_extensions:
  - abbr # 缩写
  - attr_list # 属性列表
  - admonition # 警告
  - def_list # 定义列表
  - footnotes # 脚注
  - md_in_html # 支持Markdown在HTML标签中
  - meta # 支持Markdown文件上方自定义标题标签等
  - pymdownx.caret # 上标
  - pymdownx.betterem # 更好的强调
  - pymdownx.critic # 评论
  - pymdownx.details # 细节
  - pymdownx.inlinehilite # 内联高亮
  - pymdownx.keys # 键盘
  - pymdownx.mark # 标记
  - pymdownx.snippets # 片段
  - pymdownx.smartsymbols # 符号
  - pymdownx.tilde # 删除线
  - pymdownx.superfences: #代码高亮插件
      custom_fences:
        - name: mermaid # mermaid图表
          class: mermaid # mermaid图表
          format: !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
  - pymdownx.arithmatex:  # latex支持
      generic: true # 支持latex
  - toc: 
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true # 显示行号
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji # emoji图标
      emoji_generator: !!python/name:material.extensions.emoji.to_svg   # emoji图标
  - pymdownx.tabbed:
      alternate_style: true # 交替样式
  - pymdownx.tasklist:
      custom_checkbox: true # 自定义复选框
  - markdown.extensions.toc: # 目录
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}} # 目录
      permalink: "\ue157" # 目录

# [stylesheets]
extra_javascript:
  - javascripts/extra.js  #自定义javascript
  - javascripts/mathjax.js  #Latex支持
  - javascripts/polyfill.min.js   #Latex支持
  - javascripts/tex-mml-chtml.js   #Latex支持
  - ckplayer/js/ckplayer.js #播放器配置
  - https://js.baize.host/npm/gitalk@latest/dist/gitalk.min.js  #gitalk支持
  - https://js.baize.host/npm/mermaid@10.0.2/dist/add-html-label-6e56ed67.min.js #忘了

extra_css:
  - stylesheets/extra.css # 自定义CSS
  - stylesheets/link.css  #友链配置
  # - stylesheets/video.css #播放器可选配置
  - https://js.baize.host/npm/gitalk@latest/dist/gitalk.css #gitalk支持
  - ckplayer/css/ckplayer.css   #播放器配置
  - stylesheets/font-awesome.css  # font-awesome表情支持
  # - https://cdnjs.cloudflare.com/ajax/libs/social-share.js/1.0.16/css/share.min.css  #分享支持

  - https://js.baize.host/npm/lxgw-wenkai-webfont@1.1.0/style.css  #字体
  # - https://js.baize.host/npm/lxgw-wenkai-lite-webfont@1.1.0/style.css #字体
  # - https://js.baize.host/npm/lxgw-wenkai-tc-webfont@1.0.0/style.css  #字体
  # - https://js.baize.host/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css  #字体